version: "3.9"
services:
  db:
    image: mongo:5-focal
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - db_data_dev:/data/db

volumes:
  db_data_dev:
