version: "3.3"
services:
  nodauth_db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - nodauth_db_data:/data/db

volumes:
  nodauth_db_data:
